#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f $XDG_CONFIG_HOME/X11/Xresources ] && xrdb $XDG_CONFIG_HOME/X11/Xresources

startup () {
	setxkbmap -option compose:caps
	feh --no-fehbg --randomize --recursive --bg-scale $XDG_DATA_HOME/wallpapers/*
	dunst -conf $XDG_CONFIG_HOME/dunst/dunstrc &
    #xss-lock -- lock &
	redshift-gtk -c $XDG_CONFIG_HOME/redshift/redshift.conf &
}

case $WM in 
    twin    ) startup; exec twin ;;
    *       ) startup; exec i3 > $XDG_CACHE_HOME/i3.log 2>&1 ;;
esac
