# $XDG_CONFIG_HOME/bash/bash_profile

source $HOME/.config/profile

umask 0022

if [[ -z $DISPLAY && $XDG_VTNR -eq 1 && -z $TMUX ]]; then
    sudo brightness chmod
    export BROWSER=chromium
    exec startx $XDG_CONFIG_HOME/X11/xinitrc
fi

# bashrc sources alias,etc
[ -f ~/.bashrc ] && source ~/.bashrc
